export const MATH_ADDITION = "MATH_ADDITION";
export const MATH_SUBTRACTION = "MATH_SUBTRACTION";
export const MATH_DIVISION = "MATH_DIVISION";
export const MATH_MULTIPLICATION = "MATH_MULTIPLICATION";